---
# Playbook to deploy Moonshot and its components
# TO DO

- name: "Install Moonshot with Kubernetes"
  hosts: localhost
  gather_facts: false
  roles:
    - moonshot_deploy
  tags:
    - moonshot_deploy