- name: Deploy the Postgresql Persistent Volume Claim
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'postgresql-pvc.yml') | from_yaml }}"
    state: present
    wait: true

- name: Deploy the Postgresql Service
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'postgresql-service.yml') | from_yaml }}"
    wait: true

- name: Create a service for exposing moonshot
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'moonshot-service.yml') | from_yaml }}"
    wait: true

- name: Deploy the Postgresql Deployment
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'postgresql-deployment.yml') | from_yaml }}"
    state: present
    wait: true
    wait_timeout: 180

- name: Wait till Postgres pod is created
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: default
    label_selectors:
      - app=postgres
    wait: true
    wait_sleep: 5
    wait_timeout: 180
  register: postgres_pod_info
  
- name: Wait until Postgres is ready to accept connections
  kubernetes.core.k8s_exec:
    namespace: default
    pod: "{{ postgres_pod_info.resources[0].metadata.name }}"
    command: psql -h localhost -U {{ db_user }} -d {{ db_name }} -c "\l"
  register: postgres_login
  retries: 3
  delay: 10
  until: postgres_login.rc == 0

#########> Wait for the db to be fully ready

- name: Create a Deployment for moonshot
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'moonshot-deployment.yml') | from_yaml }}"
    state: present
    wait: true
    wait_timeout: 180

- name: Wait till moonshot pod is created
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: default
    label_selectors:
      - app=moonshot
    wait: true
    wait_sleep: 5
    wait_timeout: 180
  register: moonshot_pod_info

- name: Seed the database
  kubernetes.core.k8s_exec:
    namespace: default
    pod: "{{ moonshot_pod_info.resources[0].metadata.name }}"
    command:
      - python
      - seed.py
  when: seed_database is defined and seed_database

- name: Obtain public IP
  ansible.builtin.command: "curl -s http://ifconfig.me"
  register: public_ip_result

- name: Define public IP
  ansible.builtin.lineinfile:
    path: "moonshot_deploy/vars/main.yml"
    regexp: "^app_ip:"
    line: "app_ip: {{ public_ip_result.stdout | trim }}"
    create: yes


- name: Atualizar o valor de app_ip em gcp.yml
  ansible.builtin.replace:
    path: "inventory/gcp.yml"
    regexp: "app_ip: <APP_SERVICE_IP>"
    replace: "app_ip: {{ app_ip }}"

- name: Atualizar o valor de app_port em gcp.yml
  ansible.builtin.replace:
    path: "inventory/gcp.yml"
    regexp: "app_port: <APP_PORT>"
    replace: "app_port: {{ app_port }}"