apiVersion: v1
kind: Service
metadata:
  name: "{{ service_name }}"
  labels:
    app: moonshot
    tier: webserver
  namespace: default
spec:
  type: NodePort
  selector:
    app: moonshot
  ports:
    - targetPort: 8000
      port: 80
      nodePort: 30007
