apiVersion: v1
kind: Service
metadata:
  name: "{{ service_name }}"
  labels:
    app: moonshot
    tier: webserver
  namespace: default
spec:
  selector:
    app: moonshot
  ports:
    - name: http
      protocol: TCP
      targetPort: 8000
      port: 80
  type: LoadBalancer