# Service for exposing Postgres
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: default
  labels:
    app: postgres
    tier: database
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - targetPort: 5432 # port that containers are listening on
      port: 5432 # port number exposed internally in the cluster