---
# Deployment for postgresql
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  namespace: default
  labels:
    app: postgres
    tier: database
  namespace: default
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
        tier: database
    spec:
      containers:
        - name: postgres
          image: postgres:14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "{{ db_name }}"
            - name: POSTGRES_USER
              value: "{{ db_user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ db_password }}"
          startupProbe:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - "pg_isready -h localhost -p 5432"
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
          volumeMounts:
          - name: postgresdata
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresdata
        persistentVolumeClaim:
          claimName: postgresql-pvc
